version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-1.7
      - test-1.8
      - test-1.9
      - test-1.10
jobs:
  test-1.7:
    docker:
      - image: 'circleci/golang:1.7'
    working_directory: /go/src/github.com/wmnsk/gopcua
    steps: &ref_0
      - checkout
      - run: go install ./...
      - run: go get -v -t -d ./...
      - run: go get -u golang.org/x/lint/golint
      - run: golint ./...
      - run: go test -v ./...
  test-1.8:
    docker:
      - image: 'circleci/golang:1.8'
    working_directory: /go/src/github.com/wmnsk/gopcua
    steps: *ref_0
  test-1.9:
    docker:
      - image: 'circleci/golang:1.9'
    working_directory: /go/src/github.com/wmnsk/gopcua
    steps: *ref_0
  test-1.10:
    docker:
      - image: 'circleci/golang:1.10'
    working_directory: /go/src/github.com/wmnsk/gopcua
    steps: *ref_0
